DROP TABLE IF EXISTS item;

DROP TABLE IF EXISTS item_stock;

CREATE TABLE item (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  AMOUNT bigint(20) DEFAULT NULL,
  INVENTORY_CODE bigint(20) DEFAULT NULL,
  ITEM_NO bigint(20) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  CREATED_AT datetime(6) DEFAULT NULL,
  MODIFIED_AT datetime(6) DEFAULT NULL,
  SOFT_DELETE bit(1) DEFAULT NULL,
  UUID varchar(255) DEFAULT NULL

) ;

CREATE TABLE item_stock (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ITEM_NO bigint(20) DEFAULT NULL,
  MAX_STOCK bigint(20) DEFAULT NULL,
  MIN_STOCK bigint(20) DEFAULT NULL,
  QUANTITY bigint(20) DEFAULT NULL,
  CREATED_AT datetime(6) DEFAULT NULL,
  MODIFIED_AT datetime(6) DEFAULT NULL,
  SOFT_DELETE bit(1) DEFAULT NULL,
  UUID varchar(255) DEFAULT NULL
) ;


INSERT INTO item (ID,ITEM_NO, AMOUNT ,INVENTORY_CODE ,NAME ,CREATED_AT , MODIFIED_AT ,SOFT_DELETE ,UUID )
VALUES
(1,12,23,1111189,'ITEM 1' ,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(), 0, 'ASD-FGDRE-BV'),
(2,13,45,1111190,'ITEM 2' ,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(), 0, 'ASD-FGDRE-DSWE'),
(3,14,6, 1111191,'ITEM 3' ,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(), 0, 'DDD-DDD-WWE'),
(4,15,450,1111192,'ITEM 4' ,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0, 'USS-CDD-LOK');

INSERT INTO item_stock(ID,ITEM_NO,MAX_STOCK,MIN_STOCK,QUANTITY,CREATED_AT,MODIFIED_AT,SOFT_DELETE,UUID)
VALUES
(1,12,300,5,8 ,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(), 0, 'ASD-FGDRE-BV'),
(2,13,300,5,8 ,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(), 0, 'ASD-FGDRE-DSWE'),
(3,14,300,5,8 ,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(), 0, 'DDD-DDD-WWE'),
(4,15,300,5,8 ,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0, 'USS-CDD-LOK');


